leafSize: 0.2
DistanceThresholdLine: 0.1

errorMax: 0.28
ratioMin: 0.4

# Line verticality
tiltLim: 10.0

# Info text in RViz size
textScale: 0.5







# Cropping
low_lim_x: -2.0
low_lim_y: -2.0
low_lim_z: -2.0
up_lim_x: 2.0
up_lim_y: 2.0
up_lim_z: 2.0

# Downsampling
do_downsampling: true

# Ground extraction
KSearchGround: 15
OptimizeCoefficientsGround: true
NormalDistanceWeightGround: 0.1
MaxIterationsGround: 50
DistanceThresholdGround: 0.7

# Euclidean clustering
clusterTolerance: 0.8


# KSearch for normals extraction in clusters
KSearchClusterFit: 10

# Line fitting
OptimizeCoefficientsLine: true
NormalDistanceWeightLine: 0.01
MaxIterationsLine: 1000

