# Constraints to acceptance of vertical elements
errorMax: 0.13
ratioMin: 0.4
## Max height of vertical elements
heightMax: 4.2
## Line verticality
tiltLim: 10.0


# Voxelgrid
leafSize: 0.1
minPointsVoxel: 2

# Fitting max distance
DistanceThresholdLine: 0.15

# Pointcloud collect n
nCollect: 5

# Subscription of euclidean_clustering to either "pointcloudcollected" or "pointcloudmerged" directly
subscription: pointcloudmerged

# Mahalanobis distance threshold
mahalanobisDistanceThreshold: 50.0

# Test number (1 or 2)
test: 1

# Generate log files from vertical elements, odometry, GPS or EKF
logfile: false

# When 'false', tf is map -> odom -> base_link. When true, tf is map -> ekf -> base_link
tfEKF: true

# Info text in RViz size
textScale: 0.5


delay_merge: 0.0
delay_ds: 0.0
delay_ng: 0.0
delay_cl: 0.0
delay_ve: 0.0


use_sim_time: true

# Cropping
low_lim_x: -1.80
low_lim_y: -1.80
low_lim_z: -1.80
up_lim_x: 1.80
up_lim_y: 1.80
up_lim_z: 1.80

# Downsampling
do_downsampling: true

# Ground extraction
KSearchGround: 15
OptimizeCoefficientsGround: true
NormalDistanceWeightGround: 0.1
MaxIterationsGround: 50
DistanceThresholdGround: 0.7

# Euclidean clustering
clusterTolerance: 0.48


# KSearch for normals extraction in clusters
KSearchClusterFit: 10

# Line fitting
OptimizeCoefficientsLine: true
NormalDistanceWeightLine: 0.01
MaxIterationsLine: 1000

# Car
lidarHeight: 1.9 #1.9 m
turnRate: 21.0 #21
angleOffset: -9.75 #-9.75
wheelsA: 1.7 #1.7
wheelsL: 2.46 #2.46

