# Constraints to acceptance of vertical elements
errorMax: 0.13
ratioMin: 0.4
## Max height of vertical elements
heightMax: 4.2
## Line verticality
tiltLim: 10.0


# Voxelgrid
leafSize: 0.1
minPointsVoxel: 2

# Fitting max distance
DistanceThresholdLine: 0.15

# Pointcloud collect n
nCollect: 5

# Subscription of euclidean_clustering to:
# pointcloudcollected
# pointcloudmerged
# izq/velodyne_points TODO
# der/velodyne_points TODO
subscription: pointcloudmerged

# Mahalanobis distance threshold
mahalanobisDistanceThreshold: 7.7

# Info text in RViz size
textScale: 0.5

use_sim_time: true

# Cropping (cube centered in base_link)
low_lim_x: -0.40
low_lim_y: -0.60
low_lim_z: -0.30
up_lim_x: 2.20
up_lim_y: 0.60
up_lim_z: 0.30

# Downsampling
do_downsampling: true

# Ground extraction
KSearchGround: 15
OptimizeCoefficientsGround: true
NormalDistanceWeightGround: 0.1
MaxIterationsGround: 50
DistanceThresholdGround: 0.7

# Euclidean clustering
clusterTolerance: 0.25 #0.48


# KSearch for normals extraction in clusters
KSearchClusterFit: 10

# Line fitting
OptimizeCoefficientsLine: true
NormalDistanceWeightLine: 0.01
MaxIterationsLine: 1000

# Car
lidarHeight: 1.8 #1.8 m
turnRate: 21.0 #21
angleOffset: -9.75 #-9.75
wheelsA: 1.7 #1.7
wheelsL: 2.46 #2.46

# EKF uncertainties
## For P_init
P00_init: 0.1
P11_init: 0.1
P22_init: 1.0
P33_init: 1.0
P44_init: 1.0
P55_init: 0.1
PFactor: 0.0 # Multiplies the whole matrix P by PFactor
## For Q (model)
sigma_odom_x: 0.05
sigma_odom_y: 0.008
sigma_odom_z: 1.0
sigma_odom_roll: 1.0
sigma_odom_pitch: 1.0
sigma_odom_yaw: 1.0
QFactor: 0.0015 # Multiplies the whole matrix Q by QFactor

## For R (device)
sigma_obs_x: 0.05
sigma_obs_y: 0.05
sigma_obs_z: 0.05
sigma_obs_roll: 0.007
sigma_obs_pitch: 0.007
sigma_obs_yaw: 0.035
