cloud_filename: "src/rosbags/rosbagtopcd/pcl555.pcd"

low_lim_x: -1.5
low_lim_y: -1.5
low_lim_z: -1.5
up_lim_x: 1.5
up_lim_y: 1.5
up_lim_z: 1.5

do_downsampling: false
leaf_size: 0.1

clusterTolerance: 0.6
clusterMinSize: 20
clusterMaxSize: 200
KSearch: 200
NormalDistanceWeight: 10.8
MaxIterationsFit: 1000
DistanceThresholdFit: 0.026
minRadius: 0.01
maxRadius: 0.05
