low_lim_x: -2.0
low_lim_y: -2.0
low_lim_z: -2.0
up_lim_x: 2.0
up_lim_y: 2.0
up_lim_z: 2.0

do_downsampling: true
leaf_size: 0.2

KSearchPlane: 20
NormalDistanceWeightPlane: 0.1
MaxIterationsPlane: 50
DistanceThresholdPlane: 0.7

clusterTolerance: 0.8
clusterMinSize: 10
clusterMaxSize: 150

axis_line_x: 0.1
axis_line_y: 0.1
axis_line_z: 0.8
axis_cylinder_x: 0.1
axis_cylinder_y: 0.1
axis_cylinder_z: 0.8

KSearch: 10
NormalDistanceWeight: 1.0
MaxIterationsFit: 100
DistanceThresholdFit: 0.5
minRadius: 0.0
maxRadius: 0.1
