low_lim_x: -1.5
low_lim_y: -1.5
low_lim_z: -1.5
up_lim_x: 1.5
up_lim_y: 1.5
up_lim_z: 1.5

do_downsampling: true
leaf_size: 0.1

KSearchPlane: 15

qx: 0.5
qy: 0.5
qz: 0.5
qw: -0.5

clusterTolerance: 0.8
clusterMinSize: 10
clusterMaxSize: 100
KSearch: 20
NormalDistanceWeight: 1.8
MaxIterationsFit: 50
DistanceThresholdFit: 0.05
minRadius: 0.01
maxRadius: 0.15
