# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lcm_to_ros/ibeo_objetos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lcm_to_ros.msg

class ibeo_objetos(genpy.Message):
  _md5sum = "b4a6eb791391a2364ff9033fffb47fbe"
  _type = "lcm_to_ros/ibeo_objetos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#######################################################################
# This message was automatically generated by the lcm_to_ros package
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
#######################################################################
#
# Source message:    .msg
# Creation:          lun 18 feb 2019 17:14:16 CET
#
#######################################################################
int32               timestamp_sec
int32               timestamp_nsec
int16               n_objetos
ibeo_objeto[]       objetos

================================================================================
MSG: lcm_to_ros/ibeo_objeto
#######################################################################
# This message was automatically generated by the lcm_to_ros package
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
#######################################################################
#
# Source message:    .msg
# Creation:          lun 18 feb 2019 17:14:16 CET
#
#######################################################################
int16               id
float32             age
float32             velocidad_relativa_x
float32             velocidad_relativa_y
float32             velocidad_absoluta_x
float32             velocidad_absoluta_y
float32             velocidad_absoluta_sigma_x
float32             velocidad_absoluta_sigma_y
float32             bounding_box_centro_x
float32             bounding_box_centro_y
float32             bounding_box_largo
float32             bounding_box_ancho
float32             object_box_centro_x
float32             object_box_centro_y
float32             object_box_orientacion
float32             object_box_size_x
float32             object_box_size_y
int16               clasificacion
float32             clasificacion_age
float32             clasificacion_certeza
float32             punto_cercano_x
float32             punto_cercano_y
float32             punto_referencia_x
float32             punto_referencia_y
float32             punto_referencia_sigma_x
float32             punto_referencia_sigma_y
"""
  __slots__ = ['timestamp_sec','timestamp_nsec','n_objetos','objetos']
  _slot_types = ['int32','int32','int16','lcm_to_ros/ibeo_objeto[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp_sec,timestamp_nsec,n_objetos,objetos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ibeo_objetos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp_sec is None:
        self.timestamp_sec = 0
      if self.timestamp_nsec is None:
        self.timestamp_nsec = 0
      if self.n_objetos is None:
        self.n_objetos = 0
      if self.objetos is None:
        self.objetos = []
    else:
      self.timestamp_sec = 0
      self.timestamp_nsec = 0
      self.n_objetos = 0
      self.objetos = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2ih().pack(_x.timestamp_sec, _x.timestamp_nsec, _x.n_objetos))
      length = len(self.objetos)
      buff.write(_struct_I.pack(length))
      for val1 in self.objetos:
        _x = val1
        buff.write(_get_struct_h16fh8f().pack(_x.id, _x.age, _x.velocidad_relativa_x, _x.velocidad_relativa_y, _x.velocidad_absoluta_x, _x.velocidad_absoluta_y, _x.velocidad_absoluta_sigma_x, _x.velocidad_absoluta_sigma_y, _x.bounding_box_centro_x, _x.bounding_box_centro_y, _x.bounding_box_largo, _x.bounding_box_ancho, _x.object_box_centro_x, _x.object_box_centro_y, _x.object_box_orientacion, _x.object_box_size_x, _x.object_box_size_y, _x.clasificacion, _x.clasificacion_age, _x.clasificacion_certeza, _x.punto_cercano_x, _x.punto_cercano_y, _x.punto_referencia_x, _x.punto_referencia_y, _x.punto_referencia_sigma_x, _x.punto_referencia_sigma_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.objetos is None:
        self.objetos = None
      end = 0
      _x = self
      start = end
      end += 10
      (_x.timestamp_sec, _x.timestamp_nsec, _x.n_objetos,) = _get_struct_2ih().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objetos = []
      for i in range(0, length):
        val1 = lcm_to_ros.msg.ibeo_objeto()
        _x = val1
        start = end
        end += 100
        (_x.id, _x.age, _x.velocidad_relativa_x, _x.velocidad_relativa_y, _x.velocidad_absoluta_x, _x.velocidad_absoluta_y, _x.velocidad_absoluta_sigma_x, _x.velocidad_absoluta_sigma_y, _x.bounding_box_centro_x, _x.bounding_box_centro_y, _x.bounding_box_largo, _x.bounding_box_ancho, _x.object_box_centro_x, _x.object_box_centro_y, _x.object_box_orientacion, _x.object_box_size_x, _x.object_box_size_y, _x.clasificacion, _x.clasificacion_age, _x.clasificacion_certeza, _x.punto_cercano_x, _x.punto_cercano_y, _x.punto_referencia_x, _x.punto_referencia_y, _x.punto_referencia_sigma_x, _x.punto_referencia_sigma_y,) = _get_struct_h16fh8f().unpack(str[start:end])
        self.objetos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2ih().pack(_x.timestamp_sec, _x.timestamp_nsec, _x.n_objetos))
      length = len(self.objetos)
      buff.write(_struct_I.pack(length))
      for val1 in self.objetos:
        _x = val1
        buff.write(_get_struct_h16fh8f().pack(_x.id, _x.age, _x.velocidad_relativa_x, _x.velocidad_relativa_y, _x.velocidad_absoluta_x, _x.velocidad_absoluta_y, _x.velocidad_absoluta_sigma_x, _x.velocidad_absoluta_sigma_y, _x.bounding_box_centro_x, _x.bounding_box_centro_y, _x.bounding_box_largo, _x.bounding_box_ancho, _x.object_box_centro_x, _x.object_box_centro_y, _x.object_box_orientacion, _x.object_box_size_x, _x.object_box_size_y, _x.clasificacion, _x.clasificacion_age, _x.clasificacion_certeza, _x.punto_cercano_x, _x.punto_cercano_y, _x.punto_referencia_x, _x.punto_referencia_y, _x.punto_referencia_sigma_x, _x.punto_referencia_sigma_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.objetos is None:
        self.objetos = None
      end = 0
      _x = self
      start = end
      end += 10
      (_x.timestamp_sec, _x.timestamp_nsec, _x.n_objetos,) = _get_struct_2ih().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objetos = []
      for i in range(0, length):
        val1 = lcm_to_ros.msg.ibeo_objeto()
        _x = val1
        start = end
        end += 100
        (_x.id, _x.age, _x.velocidad_relativa_x, _x.velocidad_relativa_y, _x.velocidad_absoluta_x, _x.velocidad_absoluta_y, _x.velocidad_absoluta_sigma_x, _x.velocidad_absoluta_sigma_y, _x.bounding_box_centro_x, _x.bounding_box_centro_y, _x.bounding_box_largo, _x.bounding_box_ancho, _x.object_box_centro_x, _x.object_box_centro_y, _x.object_box_orientacion, _x.object_box_size_x, _x.object_box_size_y, _x.clasificacion, _x.clasificacion_age, _x.clasificacion_certeza, _x.punto_cercano_x, _x.punto_cercano_y, _x.punto_referencia_x, _x.punto_referencia_y, _x.punto_referencia_sigma_x, _x.punto_referencia_sigma_y,) = _get_struct_h16fh8f().unpack(str[start:end])
        self.objetos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h16fh8f = None
def _get_struct_h16fh8f():
    global _struct_h16fh8f
    if _struct_h16fh8f is None:
        _struct_h16fh8f = struct.Struct("<h16fh8f")
    return _struct_h16fh8f
_struct_2ih = None
def _get_struct_2ih():
    global _struct_2ih
    if _struct_2ih is None:
        _struct_2ih = struct.Struct("<2ih")
    return _struct_2ih
