# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lcm_to_ros/mobileye_lane.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mobileye_lane(genpy.Message):
  _md5sum = "9da724a4f0dc8f5acbc944b9da5a9c67"
  _type = "lcm_to_ros/mobileye_lane"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#######################################################################
# This message was automatically generated by the lcm_to_ros package
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
#######################################################################
#
# Source message:    .msg
# Creation:          lun 18 feb 2019 17:14:16 CET
#
#######################################################################
int32               timestamp_sec
int32               timestamp_nsec
float32             curvatura
float32             heading
float32             yaw
float32             pitch
byte                flags
"""
  __slots__ = ['timestamp_sec','timestamp_nsec','curvatura','heading','yaw','pitch','flags']
  _slot_types = ['int32','int32','float32','float32','float32','float32','byte']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp_sec,timestamp_nsec,curvatura,heading,yaw,pitch,flags

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mobileye_lane, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp_sec is None:
        self.timestamp_sec = 0
      if self.timestamp_nsec is None:
        self.timestamp_nsec = 0
      if self.curvatura is None:
        self.curvatura = 0.
      if self.heading is None:
        self.heading = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.flags is None:
        self.flags = 0
    else:
      self.timestamp_sec = 0
      self.timestamp_nsec = 0
      self.curvatura = 0.
      self.heading = 0.
      self.yaw = 0.
      self.pitch = 0.
      self.flags = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i4fb().pack(_x.timestamp_sec, _x.timestamp_nsec, _x.curvatura, _x.heading, _x.yaw, _x.pitch, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.timestamp_sec, _x.timestamp_nsec, _x.curvatura, _x.heading, _x.yaw, _x.pitch, _x.flags,) = _get_struct_2i4fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i4fb().pack(_x.timestamp_sec, _x.timestamp_nsec, _x.curvatura, _x.heading, _x.yaw, _x.pitch, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.timestamp_sec, _x.timestamp_nsec, _x.curvatura, _x.heading, _x.yaw, _x.pitch, _x.flags,) = _get_struct_2i4fb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i4fb = None
def _get_struct_2i4fb():
    global _struct_2i4fb
    if _struct_2i4fb is None:
        _struct_2i4fb = struct.Struct("<2i4fb")
    return _struct_2i4fb
