(cl:in-package lcm_to_ros-msg)
(cl:export '(STR-VAL
          STR
          FLAG-VAL
          FLAG
          GNASH-VAL
          GNASH
          I8_SCALAR-VAL
          I8_SCALAR
          I8_ARRAY-VAL
          I8_ARRAY
          I16_SCALAR-VAL
          I16_SCALAR
          I16_ARRAY-VAL
          I16_ARRAY
          I32_SCALAR-VAL
          I32_SCALAR
          I32_ARRAY-VAL
          I32_ARRAY
          I64_SCALAR-VAL
          I64_SCALAR
          I64_ARRAY-VAL
          I64_ARRAY
          FLT_SCALAR-VAL
          FLT_SCALAR
          FLT_ARRAY-VAL
          FLT_ARRAY
          DBL_SCALAR-VAL
          DBL_SCALAR
          DBL_ARRAY-VAL
          DBL_ARRAY
          VARIABLE_LENGTH_ARRAY-VAL
          VARIABLE_LENGTH_ARRAY
          NUM_CHANNELS-VAL
          NUM_CHANNELS
          CHANNELS-VAL
          CHANNELS
))