(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          VELOCIDAD-VAL
          VELOCIDAD
          ACELERACION-VAL
          ACELERACION
          VELOCIDAD_RUEDAS_DELANTERAS-VAL
          VELOCIDAD_RUEDAS_DELANTERAS
          VELOCIDAD_TRASERA_IZQUIERDA-VAL
          VELOCIDAD_TRASERA_IZQUIERDA
          VELOCIDAD_TRASERA_DERECHA-VAL
          VELOCIDAD_TRASERA_DERECHA
))