(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          IDMODULO-VAL
          IDMODULO
          INPUTVOLA-VAL
          INPUTVOLA
          INPUTVOLB-VAL
          INPUTVOLB
          INPUTCORRA-VAL
          INPUTCORRA
          INPUTCORRB-VAL
          INPUTCORRB
          OUTPUTANLG1-VAL
          OUTPUTANLG1
          OUTPUTANLG2-VAL
          OUTPUTANLG2
          INPUTDIG1-VAL
          INPUTDIG1
          INPUTDIG2-VAL
          INPUTDIG2
          INPUTDIG3-VAL
          INPUTDIG3
          INPUTDIG4-VAL
          INPUTDIG4
          OUTPUTDIG1-VAL
          OUTPUTDIG1
          OUTPUTDIG2-VAL
          OUTPUTDIG2
          OUTPUTDIG3-VAL
          OUTPUTDIG3
          OUTPUTDIG4-VAL
          OUTPUTDIG4
          OUTPUTDIG5-VAL
          OUTPUTDIG5
          OUTPUTDIG6-VAL
          OUTPUTDIG6
          OUTPUTDIG7-VAL
          OUTPUTDIG7
          OUTPUTDIG8-VAL
          OUTPUTDIG8
))