(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          POSICIONX-VAL
          POSICIONX
          POSICIONY-VAL
          POSICIONY
          VELOCIDADREL-VAL
          VELOCIDADREL
          ACELERACIONX-VAL
          ACELERACIONX
          LONGITUD-VAL
          LONGITUD
          ANCHO-VAL
          ANCHO
          ANGULO-VAL
          ANGULO
          ANGLERATE-VAL
          ANGLERATE
          SCALECHANGE-VAL
          SCALECHANGE
          EDAD-VAL
          EDAD
          ID-VAL
          ID
          TIPO-VAL
          TIPO
          STATUS-VAL
          STATUS
          CARRIL-VAL
          CARRIL
          FLAGS-VAL
          FLAGS
          INTERMITENTES-VAL
          INTERMITENTES
          CUTINOUT-VAL
          CUTINOUT
))