(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          ANGULO_VOLANTE-VAL
          ANGULO_VOLANTE
          VELOCIDAD_VOLANTE-VAL
          VELOCIDAD_VOLANTE
          ANGULO_COLUMNA-VAL
          ANGULO_COLUMNA
          VELOCIDAD_COLUMNA-VAL
          VELOCIDAD_COLUMNA
          PAR_DIRECCION-VAL
          PAR_DIRECCION
          FLAG_MENSAJES-VAL
          FLAG_MENSAJES
))