(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          WX-VAL
          WX
          WY-VAL
          WY
          WZ-VAL
          WZ
          ACELX-VAL
          ACELX
          ACELY-VAL
          ACELY
          ACELZ-VAL
          ACELZ
          VELN-VAL
          VELN
          VELE-VAL
          VELE
          VELZ-VAL
          VELZ
          GPSLONG-VAL
          GPSLONG
          GPSLAT-VAL
          GPSLAT
          GPSALT-VAL
          GPSALT
          TEMP-VAL
          TEMP
          IMUTIME-VAL
          IMUTIME
          BITSTATUS-VAL
          BITSTATUS
))