(cl:in-package lcm_to_ros-msg)
(cl:export '(TIEMPO-VAL
          TIEMPO
          CALIDAD_GPS-VAL
          CALIDAD_GPS
          NRO_SATELITES-VAL
          NRO_SATELITES
          UTM_X-VAL
          UTM_X
          UTM_Y-VAL
          UTM_Y
          ORIENTACION-VAL
          ORIENTACION
          VELOCIDAD-VAL
          VELOCIDAD
          ACELERACION-VAL
          ACELERACION
          K_UTM_X-VAL
          K_UTM_X
          K_UTM_Y-VAL
          K_UTM_Y
          K_LONGITUD-VAL
          K_LONGITUD
          K_LATITUD-VAL
          K_LATITUD
          K_ORIENTACION-VAL
          K_ORIENTACION
          K_VELOCIDAD-VAL
          K_VELOCIDAD
          K_ACELERACION-VAL
          K_ACELERACION
          ANGULO_VOLANTE-VAL
          ANGULO_VOLANTE
          FLAG_MSG_GPS-VAL
          FLAG_MSG_GPS
          FLAG_MSG_CANVEL-VAL
          FLAG_MSG_CANVEL
          FLAG_MSG_CANVOL-VAL
          FLAG_MSG_CANVOL
))