(cl:in-package lcm_to_ros-msg)
(cl:export '(TIMESTAMP_SEC-VAL
          TIMESTAMP_SEC
          TIMESTAMP_NSEC-VAL
          TIMESTAMP_NSEC
          HORA-VAL
          HORA
          UTM_ESTE-VAL
          UTM_ESTE
          UTM_NORTE-VAL
          UTM_NORTE
          LONGITUD-VAL
          LONGITUD
          LATITUD-VAL
          LATITUD
          ALTURA-VAL
          ALTURA
          HDOP-VAL
          HDOP
          VELOCIDAD-VAL
          VELOCIDAD
          HEADING_VEL-VAL
          HEADING_VEL
          SEMI_MAJOR_DESV-VAL
          SEMI_MAJOR_DESV
          SEMI_MINOR_DESV-VAL
          SEMI_MINOR_DESV
          SEMI_MAJOR_ORIEN-VAL
          SEMI_MAJOR_ORIEN
          CALIDAD-VAL
          CALIDAD
          NRO_SATELITES-VAL
          NRO_SATELITES
))