; Auto-generated. Do not edit!


(cl:in-package lcm_to_ros-msg)


;//! \htmlinclude control_acelerador_orden.msg.html

(cl:defclass <control_acelerador_orden> (roslisp-msg-protocol:ros-message)
  ((Prioridad
    :reader Prioridad
    :initarg :Prioridad
    :type cl:fixnum
    :initform 0)
   (Valor
    :reader Valor
    :initarg :Valor
    :type cl:float
    :initform 0.0))
)

(cl:defclass control_acelerador_orden (<control_acelerador_orden>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <control_acelerador_orden>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'control_acelerador_orden)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lcm_to_ros-msg:<control_acelerador_orden> is deprecated: use lcm_to_ros-msg:control_acelerador_orden instead.")))

(cl:ensure-generic-function 'Prioridad-val :lambda-list '(m))
(cl:defmethod Prioridad-val ((m <control_acelerador_orden>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcm_to_ros-msg:Prioridad-val is deprecated.  Use lcm_to_ros-msg:Prioridad instead.")
  (Prioridad m))

(cl:ensure-generic-function 'Valor-val :lambda-list '(m))
(cl:defmethod Valor-val ((m <control_acelerador_orden>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcm_to_ros-msg:Valor-val is deprecated.  Use lcm_to_ros-msg:Valor instead.")
  (Valor m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <control_acelerador_orden>) ostream)
  "Serializes a message object of type '<control_acelerador_orden>"
  (cl:let* ((signed (cl:slot-value msg 'Prioridad)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'Valor))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <control_acelerador_orden>) istream)
  "Deserializes a message object of type '<control_acelerador_orden>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'Prioridad) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Valor) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<control_acelerador_orden>)))
  "Returns string type for a message object of type '<control_acelerador_orden>"
  "lcm_to_ros/control_acelerador_orden")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'control_acelerador_orden)))
  "Returns string type for a message object of type 'control_acelerador_orden"
  "lcm_to_ros/control_acelerador_orden")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<control_acelerador_orden>)))
  "Returns md5sum for a message object of type '<control_acelerador_orden>"
  "ec11058383f1828f9cecbd0a9dbdb56e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'control_acelerador_orden)))
  "Returns md5sum for a message object of type 'control_acelerador_orden"
  "ec11058383f1828f9cecbd0a9dbdb56e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<control_acelerador_orden>)))
  "Returns full string definition for message of type '<control_acelerador_orden>"
  (cl:format cl:nil "#######################################################################~%# This message was automatically generated by the lcm_to_ros package~%# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu~%#######################################################################~%#~%# Source message:    .msg~%# Creation:          lun 18 feb 2019 17:14:16 CET~%#~%#######################################################################~%int8                Prioridad~%float64             Valor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'control_acelerador_orden)))
  "Returns full string definition for message of type 'control_acelerador_orden"
  (cl:format cl:nil "#######################################################################~%# This message was automatically generated by the lcm_to_ros package~%# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu~%#######################################################################~%#~%# Source message:    .msg~%# Creation:          lun 18 feb 2019 17:14:16 CET~%#~%#######################################################################~%int8                Prioridad~%float64             Valor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <control_acelerador_orden>))
  (cl:+ 0
     1
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <control_acelerador_orden>))
  "Converts a ROS message object to a list"
  (cl:list 'control_acelerador_orden
    (cl:cons ':Prioridad (Prioridad msg))
    (cl:cons ':Valor (Valor msg))
))
