; Auto-generated. Do not edit!


(cl:in-package lcm_to_ros-msg)


;//! \htmlinclude control_caja_orden.msg.html

(cl:defclass <control_caja_orden> (roslisp-msg-protocol:ros-message)
  ((prioridad
    :reader prioridad
    :initarg :prioridad
    :type cl:fixnum
    :initform 0)
   (valor
    :reader valor
    :initarg :valor
    :type cl:float
    :initform 0.0))
)

(cl:defclass control_caja_orden (<control_caja_orden>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <control_caja_orden>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'control_caja_orden)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lcm_to_ros-msg:<control_caja_orden> is deprecated: use lcm_to_ros-msg:control_caja_orden instead.")))

(cl:ensure-generic-function 'prioridad-val :lambda-list '(m))
(cl:defmethod prioridad-val ((m <control_caja_orden>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcm_to_ros-msg:prioridad-val is deprecated.  Use lcm_to_ros-msg:prioridad instead.")
  (prioridad m))

(cl:ensure-generic-function 'valor-val :lambda-list '(m))
(cl:defmethod valor-val ((m <control_caja_orden>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcm_to_ros-msg:valor-val is deprecated.  Use lcm_to_ros-msg:valor instead.")
  (valor m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <control_caja_orden>) ostream)
  "Serializes a message object of type '<control_caja_orden>"
  (cl:let* ((signed (cl:slot-value msg 'prioridad)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'valor))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <control_caja_orden>) istream)
  "Deserializes a message object of type '<control_caja_orden>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'prioridad) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'valor) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<control_caja_orden>)))
  "Returns string type for a message object of type '<control_caja_orden>"
  "lcm_to_ros/control_caja_orden")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'control_caja_orden)))
  "Returns string type for a message object of type 'control_caja_orden"
  "lcm_to_ros/control_caja_orden")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<control_caja_orden>)))
  "Returns md5sum for a message object of type '<control_caja_orden>"
  "fccc8a5a7c3d9b41585ac5dee68ebfb2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'control_caja_orden)))
  "Returns md5sum for a message object of type 'control_caja_orden"
  "fccc8a5a7c3d9b41585ac5dee68ebfb2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<control_caja_orden>)))
  "Returns full string definition for message of type '<control_caja_orden>"
  (cl:format cl:nil "#######################################################################~%# This message was automatically generated by the lcm_to_ros package~%# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu~%#######################################################################~%#~%# Source message:    .msg~%# Creation:          lun 18 feb 2019 17:14:16 CET~%#~%#######################################################################~%int8                prioridad~%float64             valor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'control_caja_orden)))
  "Returns full string definition for message of type 'control_caja_orden"
  (cl:format cl:nil "#######################################################################~%# This message was automatically generated by the lcm_to_ros package~%# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu~%#######################################################################~%#~%# Source message:    .msg~%# Creation:          lun 18 feb 2019 17:14:16 CET~%#~%#######################################################################~%int8                prioridad~%float64             valor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <control_caja_orden>))
  (cl:+ 0
     1
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <control_caja_orden>))
  "Converts a ROS message object to a list"
  (cl:list 'control_caja_orden
    (cl:cons ':prioridad (prioridad msg))
    (cl:cons ':valor (valor msg))
))
