// Auto-generated. Do not edit!

// (in-package lcm_to_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class can_coche_habitaculo_v2 {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timestamp_sec = null;
      this.timestamp_nsec = null;
      this.frenos = null;
      this.ignicion = null;
      this.abs_activo = null;
    }
    else {
      if (initObj.hasOwnProperty('timestamp_sec')) {
        this.timestamp_sec = initObj.timestamp_sec
      }
      else {
        this.timestamp_sec = 0;
      }
      if (initObj.hasOwnProperty('timestamp_nsec')) {
        this.timestamp_nsec = initObj.timestamp_nsec
      }
      else {
        this.timestamp_nsec = 0;
      }
      if (initObj.hasOwnProperty('frenos')) {
        this.frenos = initObj.frenos
      }
      else {
        this.frenos = 0;
      }
      if (initObj.hasOwnProperty('ignicion')) {
        this.ignicion = initObj.ignicion
      }
      else {
        this.ignicion = 0;
      }
      if (initObj.hasOwnProperty('abs_activo')) {
        this.abs_activo = initObj.abs_activo
      }
      else {
        this.abs_activo = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type can_coche_habitaculo_v2
    // Serialize message field [timestamp_sec]
    bufferOffset = _serializer.int32(obj.timestamp_sec, buffer, bufferOffset);
    // Serialize message field [timestamp_nsec]
    bufferOffset = _serializer.int32(obj.timestamp_nsec, buffer, bufferOffset);
    // Serialize message field [frenos]
    bufferOffset = _serializer.int8(obj.frenos, buffer, bufferOffset);
    // Serialize message field [ignicion]
    bufferOffset = _serializer.int8(obj.ignicion, buffer, bufferOffset);
    // Serialize message field [abs_activo]
    bufferOffset = _serializer.int8(obj.abs_activo, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type can_coche_habitaculo_v2
    let len;
    let data = new can_coche_habitaculo_v2(null);
    // Deserialize message field [timestamp_sec]
    data.timestamp_sec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [timestamp_nsec]
    data.timestamp_nsec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [frenos]
    data.frenos = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [ignicion]
    data.ignicion = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [abs_activo]
    data.abs_activo = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 11;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lcm_to_ros/can_coche_habitaculo_v2';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c2b665784cea8336aa6cad167e8811e8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    #######################################################################
    # This message was automatically generated by the lcm_to_ros package
    # https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
    #######################################################################
    #
    # Source message:    .msg
    # Creation:          lun 18 feb 2019 17:14:15 CET
    #
    #######################################################################
    int32               timestamp_sec
    int32               timestamp_nsec
    int8                frenos
    int8                ignicion
    int8                abs_activo
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new can_coche_habitaculo_v2(null);
    if (msg.timestamp_sec !== undefined) {
      resolved.timestamp_sec = msg.timestamp_sec;
    }
    else {
      resolved.timestamp_sec = 0
    }

    if (msg.timestamp_nsec !== undefined) {
      resolved.timestamp_nsec = msg.timestamp_nsec;
    }
    else {
      resolved.timestamp_nsec = 0
    }

    if (msg.frenos !== undefined) {
      resolved.frenos = msg.frenos;
    }
    else {
      resolved.frenos = 0
    }

    if (msg.ignicion !== undefined) {
      resolved.ignicion = msg.ignicion;
    }
    else {
      resolved.ignicion = 0
    }

    if (msg.abs_activo !== undefined) {
      resolved.abs_activo = msg.abs_activo;
    }
    else {
      resolved.abs_activo = 0
    }

    return resolved;
    }
};

module.exports = can_coche_habitaculo_v2;
