// Auto-generated. Do not edit!

// (in-package lcm_to_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class can_coche_caja {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timestamp_sec = null;
      this.timestamp_nsec = null;
      this.marcha_palanca = null;
      this.marcha_actual = null;
      this.modo_auto = null;
    }
    else {
      if (initObj.hasOwnProperty('timestamp_sec')) {
        this.timestamp_sec = initObj.timestamp_sec
      }
      else {
        this.timestamp_sec = 0;
      }
      if (initObj.hasOwnProperty('timestamp_nsec')) {
        this.timestamp_nsec = initObj.timestamp_nsec
      }
      else {
        this.timestamp_nsec = 0;
      }
      if (initObj.hasOwnProperty('marcha_palanca')) {
        this.marcha_palanca = initObj.marcha_palanca
      }
      else {
        this.marcha_palanca = 0;
      }
      if (initObj.hasOwnProperty('marcha_actual')) {
        this.marcha_actual = initObj.marcha_actual
      }
      else {
        this.marcha_actual = 0;
      }
      if (initObj.hasOwnProperty('modo_auto')) {
        this.modo_auto = initObj.modo_auto
      }
      else {
        this.modo_auto = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type can_coche_caja
    // Serialize message field [timestamp_sec]
    bufferOffset = _serializer.int32(obj.timestamp_sec, buffer, bufferOffset);
    // Serialize message field [timestamp_nsec]
    bufferOffset = _serializer.int32(obj.timestamp_nsec, buffer, bufferOffset);
    // Serialize message field [marcha_palanca]
    bufferOffset = _serializer.int8(obj.marcha_palanca, buffer, bufferOffset);
    // Serialize message field [marcha_actual]
    bufferOffset = _serializer.int8(obj.marcha_actual, buffer, bufferOffset);
    // Serialize message field [modo_auto]
    bufferOffset = _serializer.bool(obj.modo_auto, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type can_coche_caja
    let len;
    let data = new can_coche_caja(null);
    // Deserialize message field [timestamp_sec]
    data.timestamp_sec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [timestamp_nsec]
    data.timestamp_nsec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [marcha_palanca]
    data.marcha_palanca = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [marcha_actual]
    data.marcha_actual = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [modo_auto]
    data.modo_auto = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 11;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lcm_to_ros/can_coche_caja';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ea467c83106b332ce7b80a81a2e4ae2f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    #######################################################################
    # This message was automatically generated by the lcm_to_ros package
    # https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
    #######################################################################
    #
    # Source message:    .msg
    # Creation:          lun 18 feb 2019 17:14:15 CET
    #
    #######################################################################
    int32               timestamp_sec
    int32               timestamp_nsec
    int8                marcha_palanca
    int8                marcha_actual
    bool                modo_auto
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new can_coche_caja(null);
    if (msg.timestamp_sec !== undefined) {
      resolved.timestamp_sec = msg.timestamp_sec;
    }
    else {
      resolved.timestamp_sec = 0
    }

    if (msg.timestamp_nsec !== undefined) {
      resolved.timestamp_nsec = msg.timestamp_nsec;
    }
    else {
      resolved.timestamp_nsec = 0
    }

    if (msg.marcha_palanca !== undefined) {
      resolved.marcha_palanca = msg.marcha_palanca;
    }
    else {
      resolved.marcha_palanca = 0
    }

    if (msg.marcha_actual !== undefined) {
      resolved.marcha_actual = msg.marcha_actual;
    }
    else {
      resolved.marcha_actual = 0
    }

    if (msg.modo_auto !== undefined) {
      resolved.modo_auto = msg.modo_auto;
    }
    else {
      resolved.modo_auto = false
    }

    return resolved;
    }
};

module.exports = can_coche_caja;
