// Auto-generated. Do not edit!

// (in-package lcm_to_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ibeo_objeto = require('./ibeo_objeto.js');

//-----------------------------------------------------------

class ibeo_objetos {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timestamp_sec = null;
      this.timestamp_nsec = null;
      this.n_objetos = null;
      this.objetos = null;
    }
    else {
      if (initObj.hasOwnProperty('timestamp_sec')) {
        this.timestamp_sec = initObj.timestamp_sec
      }
      else {
        this.timestamp_sec = 0;
      }
      if (initObj.hasOwnProperty('timestamp_nsec')) {
        this.timestamp_nsec = initObj.timestamp_nsec
      }
      else {
        this.timestamp_nsec = 0;
      }
      if (initObj.hasOwnProperty('n_objetos')) {
        this.n_objetos = initObj.n_objetos
      }
      else {
        this.n_objetos = 0;
      }
      if (initObj.hasOwnProperty('objetos')) {
        this.objetos = initObj.objetos
      }
      else {
        this.objetos = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ibeo_objetos
    // Serialize message field [timestamp_sec]
    bufferOffset = _serializer.int32(obj.timestamp_sec, buffer, bufferOffset);
    // Serialize message field [timestamp_nsec]
    bufferOffset = _serializer.int32(obj.timestamp_nsec, buffer, bufferOffset);
    // Serialize message field [n_objetos]
    bufferOffset = _serializer.int16(obj.n_objetos, buffer, bufferOffset);
    // Serialize message field [objetos]
    // Serialize the length for message field [objetos]
    bufferOffset = _serializer.uint32(obj.objetos.length, buffer, bufferOffset);
    obj.objetos.forEach((val) => {
      bufferOffset = ibeo_objeto.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ibeo_objetos
    let len;
    let data = new ibeo_objetos(null);
    // Deserialize message field [timestamp_sec]
    data.timestamp_sec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [timestamp_nsec]
    data.timestamp_nsec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [n_objetos]
    data.n_objetos = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [objetos]
    // Deserialize array length for message field [objetos]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.objetos = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.objetos[i] = ibeo_objeto.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 100 * object.objetos.length;
    return length + 14;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lcm_to_ros/ibeo_objetos';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b4a6eb791391a2364ff9033fffb47fbe';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    #######################################################################
    # This message was automatically generated by the lcm_to_ros package
    # https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
    #######################################################################
    #
    # Source message:    .msg
    # Creation:          lun 18 feb 2019 17:14:16 CET
    #
    #######################################################################
    int32               timestamp_sec
    int32               timestamp_nsec
    int16               n_objetos
    ibeo_objeto[]       objetos
    
    ================================================================================
    MSG: lcm_to_ros/ibeo_objeto
    #######################################################################
    # This message was automatically generated by the lcm_to_ros package
    # https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
    #######################################################################
    #
    # Source message:    .msg
    # Creation:          lun 18 feb 2019 17:14:16 CET
    #
    #######################################################################
    int16               id
    float32             age
    float32             velocidad_relativa_x
    float32             velocidad_relativa_y
    float32             velocidad_absoluta_x
    float32             velocidad_absoluta_y
    float32             velocidad_absoluta_sigma_x
    float32             velocidad_absoluta_sigma_y
    float32             bounding_box_centro_x
    float32             bounding_box_centro_y
    float32             bounding_box_largo
    float32             bounding_box_ancho
    float32             object_box_centro_x
    float32             object_box_centro_y
    float32             object_box_orientacion
    float32             object_box_size_x
    float32             object_box_size_y
    int16               clasificacion
    float32             clasificacion_age
    float32             clasificacion_certeza
    float32             punto_cercano_x
    float32             punto_cercano_y
    float32             punto_referencia_x
    float32             punto_referencia_y
    float32             punto_referencia_sigma_x
    float32             punto_referencia_sigma_y
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ibeo_objetos(null);
    if (msg.timestamp_sec !== undefined) {
      resolved.timestamp_sec = msg.timestamp_sec;
    }
    else {
      resolved.timestamp_sec = 0
    }

    if (msg.timestamp_nsec !== undefined) {
      resolved.timestamp_nsec = msg.timestamp_nsec;
    }
    else {
      resolved.timestamp_nsec = 0
    }

    if (msg.n_objetos !== undefined) {
      resolved.n_objetos = msg.n_objetos;
    }
    else {
      resolved.n_objetos = 0
    }

    if (msg.objetos !== undefined) {
      resolved.objetos = new Array(msg.objetos.length);
      for (let i = 0; i < resolved.objetos.length; ++i) {
        resolved.objetos[i] = ibeo_objeto.Resolve(msg.objetos[i]);
      }
    }
    else {
      resolved.objetos = []
    }

    return resolved;
    }
};

module.exports = ibeo_objetos;
