// Auto-generated. Do not edit!

// (in-package lcm_to_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class mobileye_tsr {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timestamp_sec = null;
      this.timestamp_nsec = null;
      this.tipo = null;
      this.valor = null;
      this.posicionX = null;
      this.posicionY = null;
      this.posicionZ = null;
    }
    else {
      if (initObj.hasOwnProperty('timestamp_sec')) {
        this.timestamp_sec = initObj.timestamp_sec
      }
      else {
        this.timestamp_sec = 0;
      }
      if (initObj.hasOwnProperty('timestamp_nsec')) {
        this.timestamp_nsec = initObj.timestamp_nsec
      }
      else {
        this.timestamp_nsec = 0;
      }
      if (initObj.hasOwnProperty('tipo')) {
        this.tipo = initObj.tipo
      }
      else {
        this.tipo = 0;
      }
      if (initObj.hasOwnProperty('valor')) {
        this.valor = initObj.valor
      }
      else {
        this.valor = 0;
      }
      if (initObj.hasOwnProperty('posicionX')) {
        this.posicionX = initObj.posicionX
      }
      else {
        this.posicionX = 0;
      }
      if (initObj.hasOwnProperty('posicionY')) {
        this.posicionY = initObj.posicionY
      }
      else {
        this.posicionY = 0;
      }
      if (initObj.hasOwnProperty('posicionZ')) {
        this.posicionZ = initObj.posicionZ
      }
      else {
        this.posicionZ = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type mobileye_tsr
    // Serialize message field [timestamp_sec]
    bufferOffset = _serializer.int32(obj.timestamp_sec, buffer, bufferOffset);
    // Serialize message field [timestamp_nsec]
    bufferOffset = _serializer.int32(obj.timestamp_nsec, buffer, bufferOffset);
    // Serialize message field [tipo]
    bufferOffset = _serializer.byte(obj.tipo, buffer, bufferOffset);
    // Serialize message field [valor]
    bufferOffset = _serializer.byte(obj.valor, buffer, bufferOffset);
    // Serialize message field [posicionX]
    bufferOffset = _serializer.byte(obj.posicionX, buffer, bufferOffset);
    // Serialize message field [posicionY]
    bufferOffset = _serializer.int8(obj.posicionY, buffer, bufferOffset);
    // Serialize message field [posicionZ]
    bufferOffset = _serializer.int8(obj.posicionZ, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type mobileye_tsr
    let len;
    let data = new mobileye_tsr(null);
    // Deserialize message field [timestamp_sec]
    data.timestamp_sec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [timestamp_nsec]
    data.timestamp_nsec = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [tipo]
    data.tipo = _deserializer.byte(buffer, bufferOffset);
    // Deserialize message field [valor]
    data.valor = _deserializer.byte(buffer, bufferOffset);
    // Deserialize message field [posicionX]
    data.posicionX = _deserializer.byte(buffer, bufferOffset);
    // Deserialize message field [posicionY]
    data.posicionY = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [posicionZ]
    data.posicionZ = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lcm_to_ros/mobileye_tsr';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a4f30ab3674f73695c4e58c6fc1ab2dd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    #######################################################################
    # This message was automatically generated by the lcm_to_ros package
    # https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu
    #######################################################################
    #
    # Source message:    .msg
    # Creation:          lun 18 feb 2019 17:14:17 CET
    #
    #######################################################################
    int32               timestamp_sec
    int32               timestamp_nsec
    byte                tipo
    byte                valor
    byte                posicionX
    int8                posicionY
    int8                posicionZ
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new mobileye_tsr(null);
    if (msg.timestamp_sec !== undefined) {
      resolved.timestamp_sec = msg.timestamp_sec;
    }
    else {
      resolved.timestamp_sec = 0
    }

    if (msg.timestamp_nsec !== undefined) {
      resolved.timestamp_nsec = msg.timestamp_nsec;
    }
    else {
      resolved.timestamp_nsec = 0
    }

    if (msg.tipo !== undefined) {
      resolved.tipo = msg.tipo;
    }
    else {
      resolved.tipo = 0
    }

    if (msg.valor !== undefined) {
      resolved.valor = msg.valor;
    }
    else {
      resolved.valor = 0
    }

    if (msg.posicionX !== undefined) {
      resolved.posicionX = msg.posicionX;
    }
    else {
      resolved.posicionX = 0
    }

    if (msg.posicionY !== undefined) {
      resolved.posicionY = msg.posicionY;
    }
    else {
      resolved.posicionY = 0
    }

    if (msg.posicionZ !== undefined) {
      resolved.posicionZ = msg.posicionZ;
    }
    else {
      resolved.posicionZ = 0
    }

    return resolved;
    }
};

module.exports = mobileye_tsr;
