// Generated by gencpp from file lcm_to_ros/cam.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_CAM_H
#define LCM_TO_ROS_MESSAGE_CAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct cam_
{
  typedef cam_<ContainerAllocator> Type;

  cam_()
    : tiempo(0.0)
    , posicion_x(0.0)
    , posicion_y(0.0)
    , velocidad(0.0)
    , orientacion(0.0)  {
    }
  cam_(const ContainerAllocator& _alloc)
    : tiempo(0.0)
    , posicion_x(0.0)
    , posicion_y(0.0)
    , velocidad(0.0)
    , orientacion(0.0)  {
  (void)_alloc;
    }



   typedef double _tiempo_type;
  _tiempo_type tiempo;

   typedef double _posicion_x_type;
  _posicion_x_type posicion_x;

   typedef double _posicion_y_type;
  _posicion_y_type posicion_y;

   typedef double _velocidad_type;
  _velocidad_type velocidad;

   typedef double _orientacion_type;
  _orientacion_type orientacion;





  typedef boost::shared_ptr< ::lcm_to_ros::cam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::cam_<ContainerAllocator> const> ConstPtr;

}; // struct cam_

typedef ::lcm_to_ros::cam_<std::allocator<void> > cam;

typedef boost::shared_ptr< ::lcm_to_ros::cam > camPtr;
typedef boost::shared_ptr< ::lcm_to_ros::cam const> camConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::cam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::cam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::cam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec97bde2f7c4b2bc5a04fa46a294e654";
  }

  static const char* value(const ::lcm_to_ros::cam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec97bde2f7c4b2bcULL;
  static const uint64_t static_value2 = 0x5a04fa46a294e654ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/cam";
  }

  static const char* value(const ::lcm_to_ros::cam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:15 CET\n\
#\n\
#######################################################################\n\
float64             tiempo\n\
float64             posicion_x\n\
float64             posicion_y\n\
float64             velocidad\n\
float64             orientacion\n\
";
  }

  static const char* value(const ::lcm_to_ros::cam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::cam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tiempo);
      stream.next(m.posicion_x);
      stream.next(m.posicion_y);
      stream.next(m.velocidad);
      stream.next(m.orientacion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::cam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::cam_<ContainerAllocator>& v)
  {
    s << indent << "tiempo: ";
    Printer<double>::stream(s, indent + "  ", v.tiempo);
    s << indent << "posicion_x: ";
    Printer<double>::stream(s, indent + "  ", v.posicion_x);
    s << indent << "posicion_y: ";
    Printer<double>::stream(s, indent + "  ", v.posicion_y);
    s << indent << "velocidad: ";
    Printer<double>::stream(s, indent + "  ", v.velocidad);
    s << indent << "orientacion: ";
    Printer<double>::stream(s, indent + "  ", v.orientacion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_CAM_H
