// Generated by gencpp from file lcm_to_ros/can_coche_habitaculo_v2.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_CAN_COCHE_HABITACULO_V2_H
#define LCM_TO_ROS_MESSAGE_CAN_COCHE_HABITACULO_V2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct can_coche_habitaculo_v2_
{
  typedef can_coche_habitaculo_v2_<ContainerAllocator> Type;

  can_coche_habitaculo_v2_()
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , frenos(0)
    , ignicion(0)
    , abs_activo(0)  {
    }
  can_coche_habitaculo_v2_(const ContainerAllocator& _alloc)
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , frenos(0)
    , ignicion(0)
    , abs_activo(0)  {
  (void)_alloc;
    }



   typedef int32_t _timestamp_sec_type;
  _timestamp_sec_type timestamp_sec;

   typedef int32_t _timestamp_nsec_type;
  _timestamp_nsec_type timestamp_nsec;

   typedef int8_t _frenos_type;
  _frenos_type frenos;

   typedef int8_t _ignicion_type;
  _ignicion_type ignicion;

   typedef int8_t _abs_activo_type;
  _abs_activo_type abs_activo;





  typedef boost::shared_ptr< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> const> ConstPtr;

}; // struct can_coche_habitaculo_v2_

typedef ::lcm_to_ros::can_coche_habitaculo_v2_<std::allocator<void> > can_coche_habitaculo_v2;

typedef boost::shared_ptr< ::lcm_to_ros::can_coche_habitaculo_v2 > can_coche_habitaculo_v2Ptr;
typedef boost::shared_ptr< ::lcm_to_ros::can_coche_habitaculo_v2 const> can_coche_habitaculo_v2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2b665784cea8336aa6cad167e8811e8";
  }

  static const char* value(const ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2b665784cea8336ULL;
  static const uint64_t static_value2 = 0xaa6cad167e8811e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/can_coche_habitaculo_v2";
  }

  static const char* value(const ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:15 CET\n\
#\n\
#######################################################################\n\
int32               timestamp_sec\n\
int32               timestamp_nsec\n\
int8                frenos\n\
int8                ignicion\n\
int8                abs_activo\n\
";
  }

  static const char* value(const ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_sec);
      stream.next(m.timestamp_nsec);
      stream.next(m.frenos);
      stream.next(m.ignicion);
      stream.next(m.abs_activo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct can_coche_habitaculo_v2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::can_coche_habitaculo_v2_<ContainerAllocator>& v)
  {
    s << indent << "timestamp_sec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_sec);
    s << indent << "timestamp_nsec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_nsec);
    s << indent << "frenos: ";
    Printer<int8_t>::stream(s, indent + "  ", v.frenos);
    s << indent << "ignicion: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ignicion);
    s << indent << "abs_activo: ";
    Printer<int8_t>::stream(s, indent + "  ", v.abs_activo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_CAN_COCHE_HABITACULO_V2_H
