// Generated by gencpp from file lcm_to_ros/can_coche_caja.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_CAN_COCHE_CAJA_H
#define LCM_TO_ROS_MESSAGE_CAN_COCHE_CAJA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct can_coche_caja_
{
  typedef can_coche_caja_<ContainerAllocator> Type;

  can_coche_caja_()
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , marcha_palanca(0)
    , marcha_actual(0)
    , modo_auto(false)  {
    }
  can_coche_caja_(const ContainerAllocator& _alloc)
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , marcha_palanca(0)
    , marcha_actual(0)
    , modo_auto(false)  {
  (void)_alloc;
    }



   typedef int32_t _timestamp_sec_type;
  _timestamp_sec_type timestamp_sec;

   typedef int32_t _timestamp_nsec_type;
  _timestamp_nsec_type timestamp_nsec;

   typedef int8_t _marcha_palanca_type;
  _marcha_palanca_type marcha_palanca;

   typedef int8_t _marcha_actual_type;
  _marcha_actual_type marcha_actual;

   typedef uint8_t _modo_auto_type;
  _modo_auto_type modo_auto;





  typedef boost::shared_ptr< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> const> ConstPtr;

}; // struct can_coche_caja_

typedef ::lcm_to_ros::can_coche_caja_<std::allocator<void> > can_coche_caja;

typedef boost::shared_ptr< ::lcm_to_ros::can_coche_caja > can_coche_cajaPtr;
typedef boost::shared_ptr< ::lcm_to_ros::can_coche_caja const> can_coche_cajaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::can_coche_caja_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea467c83106b332ce7b80a81a2e4ae2f";
  }

  static const char* value(const ::lcm_to_ros::can_coche_caja_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea467c83106b332cULL;
  static const uint64_t static_value2 = 0xe7b80a81a2e4ae2fULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/can_coche_caja";
  }

  static const char* value(const ::lcm_to_ros::can_coche_caja_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:15 CET\n\
#\n\
#######################################################################\n\
int32               timestamp_sec\n\
int32               timestamp_nsec\n\
int8                marcha_palanca\n\
int8                marcha_actual\n\
bool                modo_auto\n\
";
  }

  static const char* value(const ::lcm_to_ros::can_coche_caja_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_sec);
      stream.next(m.timestamp_nsec);
      stream.next(m.marcha_palanca);
      stream.next(m.marcha_actual);
      stream.next(m.modo_auto);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct can_coche_caja_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::can_coche_caja_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::can_coche_caja_<ContainerAllocator>& v)
  {
    s << indent << "timestamp_sec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_sec);
    s << indent << "timestamp_nsec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_nsec);
    s << indent << "marcha_palanca: ";
    Printer<int8_t>::stream(s, indent + "  ", v.marcha_palanca);
    s << indent << "marcha_actual: ";
    Printer<int8_t>::stream(s, indent + "  ", v.marcha_actual);
    s << indent << "modo_auto: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.modo_auto);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_CAN_COCHE_CAJA_H
