// Generated by gencpp from file lcm_to_ros/control_caja_orden.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_CONTROL_CAJA_ORDEN_H
#define LCM_TO_ROS_MESSAGE_CONTROL_CAJA_ORDEN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct control_caja_orden_
{
  typedef control_caja_orden_<ContainerAllocator> Type;

  control_caja_orden_()
    : prioridad(0)
    , valor(0.0)  {
    }
  control_caja_orden_(const ContainerAllocator& _alloc)
    : prioridad(0)
    , valor(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _prioridad_type;
  _prioridad_type prioridad;

   typedef double _valor_type;
  _valor_type valor;





  typedef boost::shared_ptr< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> const> ConstPtr;

}; // struct control_caja_orden_

typedef ::lcm_to_ros::control_caja_orden_<std::allocator<void> > control_caja_orden;

typedef boost::shared_ptr< ::lcm_to_ros::control_caja_orden > control_caja_ordenPtr;
typedef boost::shared_ptr< ::lcm_to_ros::control_caja_orden const> control_caja_ordenConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::control_caja_orden_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fccc8a5a7c3d9b41585ac5dee68ebfb2";
  }

  static const char* value(const ::lcm_to_ros::control_caja_orden_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfccc8a5a7c3d9b41ULL;
  static const uint64_t static_value2 = 0x585ac5dee68ebfb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/control_caja_orden";
  }

  static const char* value(const ::lcm_to_ros::control_caja_orden_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:16 CET\n\
#\n\
#######################################################################\n\
int8                prioridad\n\
float64             valor\n\
";
  }

  static const char* value(const ::lcm_to_ros::control_caja_orden_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prioridad);
      stream.next(m.valor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_caja_orden_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::control_caja_orden_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::control_caja_orden_<ContainerAllocator>& v)
  {
    s << indent << "prioridad: ";
    Printer<int8_t>::stream(s, indent + "  ", v.prioridad);
    s << indent << "valor: ";
    Printer<double>::stream(s, indent + "  ", v.valor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_CONTROL_CAJA_ORDEN_H
