// Generated by gencpp from file lcm_to_ros/mobileye_tsr.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_MOBILEYE_TSR_H
#define LCM_TO_ROS_MESSAGE_MOBILEYE_TSR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct mobileye_tsr_
{
  typedef mobileye_tsr_<ContainerAllocator> Type;

  mobileye_tsr_()
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , tipo(0)
    , valor(0)
    , posicionX(0)
    , posicionY(0)
    , posicionZ(0)  {
    }
  mobileye_tsr_(const ContainerAllocator& _alloc)
    : timestamp_sec(0)
    , timestamp_nsec(0)
    , tipo(0)
    , valor(0)
    , posicionX(0)
    , posicionY(0)
    , posicionZ(0)  {
  (void)_alloc;
    }



   typedef int32_t _timestamp_sec_type;
  _timestamp_sec_type timestamp_sec;

   typedef int32_t _timestamp_nsec_type;
  _timestamp_nsec_type timestamp_nsec;

   typedef int8_t _tipo_type;
  _tipo_type tipo;

   typedef int8_t _valor_type;
  _valor_type valor;

   typedef int8_t _posicionX_type;
  _posicionX_type posicionX;

   typedef int8_t _posicionY_type;
  _posicionY_type posicionY;

   typedef int8_t _posicionZ_type;
  _posicionZ_type posicionZ;





  typedef boost::shared_ptr< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> const> ConstPtr;

}; // struct mobileye_tsr_

typedef ::lcm_to_ros::mobileye_tsr_<std::allocator<void> > mobileye_tsr;

typedef boost::shared_ptr< ::lcm_to_ros::mobileye_tsr > mobileye_tsrPtr;
typedef boost::shared_ptr< ::lcm_to_ros::mobileye_tsr const> mobileye_tsrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4f30ab3674f73695c4e58c6fc1ab2dd";
  }

  static const char* value(const ::lcm_to_ros::mobileye_tsr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4f30ab3674f7369ULL;
  static const uint64_t static_value2 = 0x5c4e58c6fc1ab2ddULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/mobileye_tsr";
  }

  static const char* value(const ::lcm_to_ros::mobileye_tsr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:17 CET\n\
#\n\
#######################################################################\n\
int32               timestamp_sec\n\
int32               timestamp_nsec\n\
byte                tipo\n\
byte                valor\n\
byte                posicionX\n\
int8                posicionY\n\
int8                posicionZ\n\
";
  }

  static const char* value(const ::lcm_to_ros::mobileye_tsr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_sec);
      stream.next(m.timestamp_nsec);
      stream.next(m.tipo);
      stream.next(m.valor);
      stream.next(m.posicionX);
      stream.next(m.posicionY);
      stream.next(m.posicionZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mobileye_tsr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::mobileye_tsr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::mobileye_tsr_<ContainerAllocator>& v)
  {
    s << indent << "timestamp_sec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_sec);
    s << indent << "timestamp_nsec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp_nsec);
    s << indent << "tipo: ";
    Printer<int8_t>::stream(s, indent + "  ", v.tipo);
    s << indent << "valor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.valor);
    s << indent << "posicionX: ";
    Printer<int8_t>::stream(s, indent + "  ", v.posicionX);
    s << indent << "posicionY: ";
    Printer<int8_t>::stream(s, indent + "  ", v.posicionY);
    s << indent << "posicionZ: ";
    Printer<int8_t>::stream(s, indent + "  ", v.posicionZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_MOBILEYE_TSR_H
