// Generated by gencpp from file lcm_to_ros/trayectoria.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_TRAYECTORIA_H
#define LCM_TO_ROS_MESSAGE_TRAYECTORIA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct trayectoria_
{
  typedef trayectoria_<ContainerAllocator> Type;

  trayectoria_()
    : n_puntos(0)
    , puntos_x()
    , puntos_y()  {
    }
  trayectoria_(const ContainerAllocator& _alloc)
    : n_puntos(0)
    , puntos_x(_alloc)
    , puntos_y(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _n_puntos_type;
  _n_puntos_type n_puntos;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _puntos_x_type;
  _puntos_x_type puntos_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _puntos_y_type;
  _puntos_y_type puntos_y;





  typedef boost::shared_ptr< ::lcm_to_ros::trayectoria_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::trayectoria_<ContainerAllocator> const> ConstPtr;

}; // struct trayectoria_

typedef ::lcm_to_ros::trayectoria_<std::allocator<void> > trayectoria;

typedef boost::shared_ptr< ::lcm_to_ros::trayectoria > trayectoriaPtr;
typedef boost::shared_ptr< ::lcm_to_ros::trayectoria const> trayectoriaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::trayectoria_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::trayectoria_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::trayectoria_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::trayectoria_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::trayectoria_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54dcf0af9a01e22cc6b946a83e674019";
  }

  static const char* value(const ::lcm_to_ros::trayectoria_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54dcf0af9a01e22cULL;
  static const uint64_t static_value2 = 0xc6b946a83e674019ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/trayectoria";
  }

  static const char* value(const ::lcm_to_ros::trayectoria_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:17 CET\n\
#\n\
#######################################################################\n\
int32               n_puntos\n\
float64[]           puntos_x\n\
float64[]           puntos_y\n\
";
  }

  static const char* value(const ::lcm_to_ros::trayectoria_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n_puntos);
      stream.next(m.puntos_x);
      stream.next(m.puntos_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trayectoria_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::trayectoria_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::trayectoria_<ContainerAllocator>& v)
  {
    s << indent << "n_puntos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_puntos);
    s << indent << "puntos_x[]" << std::endl;
    for (size_t i = 0; i < v.puntos_x.size(); ++i)
    {
      s << indent << "  puntos_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.puntos_x[i]);
    }
    s << indent << "puntos_y[]" << std::endl;
    for (size_t i = 0; i < v.puntos_y.size(); ++i)
    {
      s << indent << "  puntos_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.puntos_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_TRAYECTORIA_H
