// Generated by gencpp from file lcm_to_ros/warnings_coche.msg
// DO NOT EDIT!


#ifndef LCM_TO_ROS_MESSAGE_WARNINGS_COCHE_H
#define LCM_TO_ROS_MESSAGE_WARNINGS_COCHE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lcm_to_ros
{
template <class ContainerAllocator>
struct warnings_coche_
{
  typedef warnings_coche_<ContainerAllocator> Type;

  warnings_coche_()
    : tipo_obs(0)
    , longitud(0.0)
    , latitud(0.0)
    , velocidad(0.0)  {
    }
  warnings_coche_(const ContainerAllocator& _alloc)
    : tipo_obs(0)
    , longitud(0.0)
    , latitud(0.0)
    , velocidad(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _tipo_obs_type;
  _tipo_obs_type tipo_obs;

   typedef double _longitud_type;
  _longitud_type longitud;

   typedef double _latitud_type;
  _latitud_type latitud;

   typedef double _velocidad_type;
  _velocidad_type velocidad;





  typedef boost::shared_ptr< ::lcm_to_ros::warnings_coche_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcm_to_ros::warnings_coche_<ContainerAllocator> const> ConstPtr;

}; // struct warnings_coche_

typedef ::lcm_to_ros::warnings_coche_<std::allocator<void> > warnings_coche;

typedef boost::shared_ptr< ::lcm_to_ros::warnings_coche > warnings_cochePtr;
typedef boost::shared_ptr< ::lcm_to_ros::warnings_coche const> warnings_cocheConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcm_to_ros::warnings_coche_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcm_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lcm_to_ros': ['/home/alberto/workspaces/workspace14diciembre/src/lcm_to_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcm_to_ros::warnings_coche_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcm_to_ros::warnings_coche_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcm_to_ros::warnings_coche_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d63e4b099b36145ebd6de918f9a6bd94";
  }

  static const char* value(const ::lcm_to_ros::warnings_coche_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd63e4b099b36145eULL;
  static const uint64_t static_value2 = 0xbd6de918f9a6bd94ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcm_to_ros/warnings_coche";
  }

  static const char* value(const ::lcm_to_ros::warnings_coche_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#######################################################################\n\
# This message was automatically generated by the lcm_to_ros package\n\
# https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu\n\
#######################################################################\n\
#\n\
# Source message:    .msg\n\
# Creation:          lun 18 feb 2019 17:14:17 CET\n\
#\n\
#######################################################################\n\
int8                tipo_obs\n\
float64             longitud\n\
float64             latitud\n\
float64             velocidad\n\
";
  }

  static const char* value(const ::lcm_to_ros::warnings_coche_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tipo_obs);
      stream.next(m.longitud);
      stream.next(m.latitud);
      stream.next(m.velocidad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct warnings_coche_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcm_to_ros::warnings_coche_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcm_to_ros::warnings_coche_<ContainerAllocator>& v)
  {
    s << indent << "tipo_obs: ";
    Printer<int8_t>::stream(s, indent + "  ", v.tipo_obs);
    s << indent << "longitud: ";
    Printer<double>::stream(s, indent + "  ", v.longitud);
    s << indent << "latitud: ";
    Printer<double>::stream(s, indent + "  ", v.latitud);
    s << indent << "velocidad: ";
    Printer<double>::stream(s, indent + "  ", v.velocidad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCM_TO_ROS_MESSAGE_WARNINGS_COCHE_H
